apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-price-prediction-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flight-price-prediction
  template:
    metadata:
      labels:
        app: flight-price-prediction
    spec:
      containers:
      - name: flight-price-prediction
        image: satyamkulkarni122/flight-price-prediction-image:v1
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: flight-price-prediction-service
spec:
  selector:
    app: flight-price-prediction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

